"""
Generate the C table of stat-name -> CRC-32 keys the scanner searches for.

The engine never stores the stat NAME (see tools/DevAccess/MP_STATS.md): the
runtime key is a CStringID, which for this call site is raw CRC-32 of the
exact-case string. So the stat table in memory is findable by looking for those
u32 values -- and a CLUSTER of several distinct ones in a small address range
is almost certainly the table itself rather than a coincidence.
"""
import json, os

SRC = r"C:\Users\sambe\Desktop\......DEV\Avatar_Level_Editor\tools\DevAccess\mp_stats.json"
DST = (r"C:\Users\sambe\Desktop\......DEV\Avatar_Level_Editor\tools"
       r"\console_dll\console_dll\mp_stat_hashes.h")

data = json.load(open(SRC))
names = data['names']

# Multiplayer only -- the 21 FCXSingle stats are inert Far Cry 2 leftovers
# (diamond_found, npc_machete_killed) and would only add false positives.
mp = [n for n in names if n['in_modes'] != ['FCXSingle']]
mp.sort(key=lambda n: int(n['crc32'], 16))          # sorted: scanner bisects

lines = []
lines.append('/* GENERATED by tools/mp_stats/gen_stat_hashes.py - do not edit.')
lines.append(' *')
lines.append(' * Every multiplayer stat in gamemodesconfig.xml, with the CRC-32 the engine')
lines.append(' * keys it by. EXACT CASE, no folding -- see tools/DevAccess/MP_STATS.md; the')
lines.append(' * <Stat> parser passes flag 0 to FUN_100ED6A0, selecting FUN_10103240.')
lines.append(' *')
lines.append(' * SORTED BY HASH so the scanner can bisect instead of scanning 84 entries')
lines.append(' * per candidate dword.')
lines.append(' */')
lines.append('#ifndef MP_STAT_HASHES_H')
lines.append('#define MP_STAT_HASHES_H')
lines.append('')
lines.append('typedef struct { unsigned long hash; const char* name; } MpStatName;')
lines.append('')
lines.append('static const MpStatName kMpStatNames[] = {')
for n in mp:
    lines.append('    { 0x%sUL, "%s" },' % (n['crc32'], n['name']))
lines.append('};')
lines.append('#define MP_STAT_COUNT %d' % len(mp))
lines.append('')
lines.append('#endif /* MP_STAT_HASHES_H */')

open(DST, 'w', encoding='ascii', newline='\n').write('\n'.join(lines) + '\n')

vals = [int(n['crc32'], 16) for n in mp]
print("wrote %s" % DST)
print("multiplayer stats: %d" % len(mp))
print("sorted ascending : %s" % (vals == sorted(vals)))
print("unique           : %s" % (len(set(vals)) == len(vals)))
print("\nthe ones that matter most:")
for want in ('kills', 'deaths', 'score', 'xp', 'headshotKills', 'meleeKills'):
    for n in mp:
        if n['name'] == want:
            print("   %-16s 0x%s" % (want, n['crc32']))
