/* Generated by mp_spawnpoints.py - do not hand-edit.
   A spawn point that exists in each mp_* world, so `warp` can
   call ChangeWorld with a real id instead of the -1/-1 default
   that no multiplayer world can resolve. */
typedef struct { const char* world; unsigned long lo, hi; } MpSpawn;
static const MpSpawn g_mpSpawns[] = {
    { "mp_ancientgrounds_03", 0x59600020UL, 0x1CA45EB0UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_14 */
    { "mp_bluelagoon_rb_01", 0x32E017C7UL, 0x1C9C9D2BUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_5 */
    { "mp_brokencage_rf_01", 0x44A017B1UL, 0x1C9BF8A9UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_9 */
    { "mp_dustbowl_rb_01", 0x77400823UL, 0x1CA46832UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_17 */
    { "mp_fogswamp_rb_01", 0xDB800675UL, 0x1CA46894UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_10 */
    { "mp_forsakencaldera_rf_01", 0xC3E01960UL, 0x1C9BE01DUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_4 */
    { "mp_gravesbog_rb_01", 0x3F20186FUL, 0x1C9C289BUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_1 */
    { "mp_hellsgate_02", 0x96A00057UL, 0x1CA45E45UL },   /* SpawnPoints.SpawnPointRedStart.Multi_15 */
    { "mp_hometree", 0x3C2017A7UL, 0x1C9C74AEUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_4 */
    { "mp_jeannormand_of_01", 0x07C006ACUL, 0x1CA37B07UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_8 */
    { "mp_jeannormand_rf_02", 0x9A6010FDUL, 0x1CA46923UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_15 */
    { "mp_kowecave_fm_01", 0x57C0117EUL, 0x1C9C83CDUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_0 */
    { "mp_kowevillage_fm_01", 0xF6C006B0UL, 0x1CA45F39UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_8 */
    { "mp_mridge_df_01", 0x086000ACUL, 0x1C98713EUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_6 */
    { "mp_needlehills_rb_01", 0x6D201917UL, 0x1C9C2BD3UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_3 */
    { "mp_ps3map", 0xAF800C9BUL, 0x1CA1F6ABUL },   /* SpawnPoints.SpawnPointBlue.Multi_0 */
    { "mp_vaderashollow_fm_01", 0x1320053BUL, 0x1CA45EE4UL },   /* SpawnPoints.SpawnPointBlueStart.Multi_8 */
    { "mp_verdantpinnacle_fm_01", 0x3A8007DDUL, 0x1CA1F63DUL },   /* SpawnPoints.SpawnPointBlueStart.Multi_2 */
};
#define MP_SPAWN_COUNT 18
