"""Extract a usable spawn point id for every multiplayer world.

WHY. `warp` calls the engine's `GameChangeWorldDefaultSpawnPoint(world)`, which
is a thin wrapper over `ChangeWorld(world, spawnLo, spawnHi)` with the id
hardcoded to the engine's -1/-1 "no spawn point, you pick" sentinel:

    1063E613  or ecx, 0xffffffff  ; push ecx   <- lo = -1
    1063E617  or eax, 0xffffffff  ; push eax   <- hi = -1
    1063E657  call 0x1063E4E0                  <- the real change-world

Single-player worlds have a default it can pick. Multiplayer worlds do not:
their spawn points are `SpawnPoints.*.Multi`, placed by the map and resolved by
an MP spawn-point service that only exists inside a real match - and a warp
never starts one. So the load enters the world change and never comes back:
the frame loop stops ticking entirely (`[wdog] no detour for 57735ms`), which
is why the console cannot be opened to fix it from inside, and why the player
comes out null (`[rescue] player=00000000`).

The ids are static map data, so they can be read here, offline, and handed to
the DLL as a table. `mapsdata.fcb` carries them:

    <field name="hidName"     value-String="SpawnPoints.SpawnPointBlueStart.Multi_0" />
    <field name="disEntityId" value-Id64="2061695535055640499" BinHex="B31700722A9D9C1C" />

PREFERENCE ORDER is deliberate. `*Start*` spawns are where a match actually
begins, so they are the ones most likely to sit on valid ground with the map's
geometry around them; a plain `SpawnPointRed`/`Blue` is a respawn point and a
`Spectator` one may be parked off the map entirely. Spectator is never chosen.

    python mp_spawnpoints.py            print the table
    python mp_spawnpoints.py --c        emit the C table for avatar_console.c
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EDITOR = os.path.join(os.path.dirname(os.path.dirname(HERE)), "Editor")
sys.path.insert(0, EDITOR)

from avmodel import resolve, kitlib                      # noqa: E402

#: Best first. A match starts at a *Start* point, so that is the safest bet for
#: "somewhere inside this map with ground under it".
PREF = ("SpawnPointBlueStart", "SpawnPointRedStart",
        "SpawnPointBlue", "SpawnPointRed", "SpawnPoint")

_FIELD = re.compile(
    r'name="hidName"\s+value-String="([^"]+)"[^>]*>.*?'
    r'name="disEntityId"\s+value-Id64="(\d+)"', re.S)


def spawns_for(world):
    """-> [(instance name, 64-bit id), ...] found in this world's mapsdata."""
    d = os.path.join(resolve.DATA, "worlds", world, "generated")
    if not os.path.isdir(d):
        return []
    cand = [f for f in os.listdir(d) if f.endswith(".mapsdata.fcb")]
    if not cand:
        return []
    try:
        xml = kitlib._fcb_xml(os.path.join(d, cand[0]))
    except Exception:
        return []
    out = []
    for name, i64 in _FIELD.findall(xml):
        if "SpawnPoints." in name and ".Multi" in name:
            out.append((name, int(i64)))
    return out


def pick(spawns):
    """The one to warp to. -> (name, id) or None."""
    for want in PREF:
        for name, i in spawns:
            if "Spectator" in name:
                continue
            if want in name:
                return name, i
    for name, i in spawns:                 # anything at all, except spectator
        if "Spectator" not in name:
            return name, i
    return None


def main():
    worlds = sorted(d for d in os.listdir(os.path.join(resolve.DATA, "worlds"))
                    if d.startswith("mp_"))
    rows = []
    for wname in worlds:
        sp = spawns_for(wname)
        got = pick(sp)
        rows.append((wname, len(sp), got))

    if "--c" in sys.argv:
        print("/* Generated by mp_spawnpoints.py - do not hand-edit.")
        print("   A spawn point that exists in each mp_* world, so `warp` can")
        print("   call ChangeWorld with a real id instead of the -1/-1 default")
        print("   that no multiplayer world can resolve. */")
        print("typedef struct { const char* world; unsigned long lo, hi; }"
              " MpSpawn;")
        print("static const MpSpawn g_mpSpawns[] = {")
        for wname, _n, got in rows:
            if not got:
                print('    /* %-30s no SpawnPoints.*.Multi found */' % wname)
                continue
            name, i = got
            print('    { "%s", 0x%08XUL, 0x%08XUL },   /* %s */'
                  % (wname, i & 0xFFFFFFFF, (i >> 32) & 0xFFFFFFFF, name))
        print("};")
        print("#define MP_SPAWN_COUNT %d"
              % sum(1 for _w, _n, g in rows if g))
        return 0

    print("%-32s %5s  %-42s %s" % ("world", "pts", "chosen", "id (lo:hi)"))
    miss = 0
    for wname, n, got in rows:
        if not got:
            miss += 1
            print("%-32s %5d  %-42s %s" % (wname, n, "-", "NONE FOUND"))
            continue
        name, i = got
        print("%-32s %5d  %-42s %08X:%08X"
              % (wname, n, name[:42], i & 0xFFFFFFFF, (i >> 32) & 0xFFFFFFFF))
    print("\n%d world(s), %d without a usable spawn point" % (len(rows), miss))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
